# Generated by Django 3.1.1 on 2020-09-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20200920_2358'),
        ('core', '0002_auto_20200920_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='attractions',
            field=models.ManyToManyField(to='attractions.Attractions'),
        ),
    ]
