# Generated by Django 3.1.1 on 2020-09-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('core', '0003_pontoturistico_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='comment',
            field=models.ManyToManyField(to='comment.Comment'),
        ),
    ]
