# Generated by Django 3.1.1 on 2020-09-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('core', '0004_pontoturistico_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='assessments',
            field=models.ManyToManyField(to='assessments.Assessments'),
        ),
    ]
