# Generated by Django 3.1.1 on 2020-09-21 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0002_adresses_linha2'),
        ('core', '0005_pontoturistico_assessments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='adresses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adresses.adresses'),
            preserve_default=False,
        ),
    ]
