# Generated by Django 3.1.1 on 2020-09-21 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0002_adresses_linha2'),
        ('core', '0006_pontoturistico_adresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='adresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresses.adresses'),
        ),
    ]
