# Generated by Django 3.1.1 on 2020-09-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresses',
            name='linha2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
