# Generated by Django 3.1.1 on 2020-09-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='idade_minima',
            field=models.IntegerField(),
        ),
    ]
